name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. SSH로 EC2에 연결해 Docker Compose 실행
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/NewsPulse
          git pull origin main
          docker-compose down
          docker-compose up --build -d
