name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Deploy to EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 퍼블릭 IP 또는 도메인
          username: ${{ secrets.EC2_USER }}  # EC2 사용자 이름
          key: ${{ secrets.EC2_SSH_KEY }}  # SSH 프라이빗 키
          port: 22  # 기본 SSH 포트
          script: |
            echo "==== Starting Debugging ===="
            ssh -v -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} echo "SSH Connection Successful" || echo "SSH Connection Failed"
            whoami  # 현재 SSH 사용자를 확인
            cd ~/NewsPulse  # 프로젝트 경로로 이동
            git pull origin main  # 최신 코드 가져오기
            docker-compose down  # 기존 컨테이너 종료
            docker-compose up --build -d  # 새 컨테이너 빌드 및 실행
