name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. SSH to EC2 and deploy the application
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 퍼블릭 IP
          username: ${{ secrets.EC2_USER }}  # 보통 ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}  # EC2 접근용 .pem 파일의 내용
          port: 22  # 기본 SSH 포트
          script: |
            whoami  # 현재 SSH 사용자가 누구인지 확인
            cd ~/NewsPulse  # 프로젝트 경로로 이동
            git pull origin main  # 최신 코드 가져오기
            docker-compose down  # 기존 컨테이너 종료
            docker-compose up --build -d  # 새 컨테이너 빌드 및 실행
